### ISSUE TITLE
Search result warning: uasort() expects parameter 1 to be array

### ISSUE THREAD

**Issue by Pixie74943** [govCMS/GovCMS7#195]
I am inconsistently getting the following warning when using the search engine my govCMS site:

Warning: uasort() expects parameter 1 to be array, null given in node_view_multiple() (line 2679 of /mnt/www/html/govcms01live/docroot/modules/node/node.module).

I can't seem to find a consistent reasoning behind this error - currently it is throwing the error when I search for "mobile communications" which returns no results. However other searches with zero results are not throwing this error. This can be viewed on the DECD website by govCMS members with access.

I have found [the following patch](https://www.drupal.org/node/2392289) for the Search API pages module which appears to be aimed at fixing this issue. From what I can see this was pulled into version 7.x-1.2 of the Search API pages module, and govCMS is currently using version 7x-1.1.

If this patch is likely to solve the issue, can we look at getting the module updated in the govCMS system. Otherwise I would appreciate someone pointing me in the right direction for a possible fix.

**Comment by aleayr** [comment]
@Pixie74943, is there a screenshot or steps to reproduce this one? I just jumped onto your site, and typed in "mobile communications" but doesn't throw the error on my screen.

**Comment by fiasco** [comment]
Perhaps we upgrade the module anyway? That should be fairly low risk, I don't believe we track any patches against Search API module currently.

**Comment by fiasco** [comment]
This will likely be resolved in #185

**Comment by Pixie74943** [comment]
Cheers @fiasco 

I've subscribed to the 185, so once that goes through I'll retest on our site and see if the issue is resolved.

**Comment by Feng-Shui** [comment]
We're seeing this too, will keep an eye on #185.

**Comment by Pixie74943** [comment]
This issue is still showing on our site 8 days after the patch was merged.

Strangely we got the same error when creating a node with a file upload.

![error on search](https://cloud.githubusercontent.com/assets/13777586/14094959/a975163c-f5a2-11e5-916b-3273c4e54ec4.PNG)
![error on upload](https://cloud.githubusercontent.com/assets/13777586/14094960/a9787732-f5a2-11e5-9b31-d373f8487ad6.png)

**Comment by fiasco** [comment]
@Pixie74943 we've merged the change into the source codebase, but we've not yet cut a new release. So the merged change hasn't been released to the platform yet. You can view all the releases and their changes here: https://www.drupal.org/node/2366707/release

7.x-2.0-beta10 will have this fix in it.

**Comment by Pixie74943** [comment]
Ah, cheers thanks
